DELIMITER $$

CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON SpotifyClone.USUARIOS
FOR EACH ROW
BEGIN
DELETE FROM SpotifyClone.USUARIO_ARTISTA
WHERE USUARIO_ID = OLD.USUARIO_ID;
DELETE FROM SpotifyClone.USUARIO_CANCOES
WHERE USUARIO_ID = OLD.USUARIO_ID;
END $$
DELIMITER ;
