CREATE VIEW perfil_artistas AS
SELECT ART.NOME_ARTISTA AS artista,
ALB.NOME_ALBUM AS album,
COUNT(UA.ARTISTA_ID) AS seguidores
FROM SpotifyClone.ARTISTAS AS ART
INNER JOIN SpotifyClone.ALBUNS AS ALB ON ART.ARTISTA_ID = ALB.ARTISTA_ID
INNER JOIN SpotifyClone.USUARIO_ARTISTA AS UA ON ALB.ARTISTA_ID = UA.ARTISTA_ID
GROUP BY UA.ARTISTA_ID, album
ORDER BY seguidores DESC, artista, album;
