DELIMITER $$
CREATE PROCEDURE albuns_do_artista(IN nome_artista VARCHAR(40))
BEGIN
SELECT ART.NOME_ARTISTA AS artista,
ALB.NOME_ALBUM AS album
FROM SpotifyClone.ARTISTAS AS ART
INNER JOIN SpotifyClone.ALBUNS AS ALB ON ART.ARTISTA_ID = ALB.ARTISTA_ID
WHERE ART.NOME_ARTISTA = nome_artista
ORDER BY ALB.NOME_ALBUM;
END $$
DELIMITER ;
