CREATE VIEW top_3_artistas AS
SELECT A.NOME_ARTISTA AS artista,
COUNT(UA.ARTISTA_ID) AS seguidores
FROM SpotifyClone.ARTISTAS AS A
INNER JOIN USUARIO_ARTISTA AS UA ON A.ARTISTA_ID = UA.ARTISTA_ID
GROUP BY UA.ARTISTA_ID
ORDER BY seguidores DESC, artista
LIMIT 3;
